// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyvbnqouhkbbiassluea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5dmJucW91aGtiYmlhc3NsdWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1ODUwNDUsImV4cCI6MjA3NDE2MTA0NX0.l34bd_HLF8b5UJQVANhk992CIho912o2-mYUNZ60u90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});